namespace: hyperhcp
name: jwt_token
version: 0.1.0
readme: README.md
authors:
  - Hugues Granger (@huguesgr)
  - Fabio Isgrò (@dr_gogeta86)
description: Based on Hugues Granger's "jwks_jwt"
license:
  - MIT
# license_file: ''
tags:
  - 'jwks'
  - 'jwt'
dependencies: {}
repository: https://github.com/huguesgr/jwks_jwt
issues: https://github.com/huguesgr/jwks_jwt/issues
build_ignore:
  - 'venv'
